### ISSUE TITLE
Посты не отображаются для незалогиненных пользователей

### ISSUE THREAD

**Issue by abnormalize0** [abnormalize0/DailyTeleFrog#102]
Вопреки документации, если у пользователя id 0 или -1 то метод api_pages_get() не возвращает посты для него. Нужно исправить этот баг.

**Comment by abnormalize0** [comment]
Запрос:
```
const request = await fetch("http://127.0.0.1:5000/pages", {
    method: 'GET',
    headers: {
        'indexes': "~"+page+"~",
        'user-id': localStorage.id,
        'include-nonsub': true,
        'sort-column': 'creation_date',
        'sort-direction': "descending"
    }
})
```
Запись в логах:
```
2024-01-30 21:01:39,635 INFO Got request api_pages_get
2024-01-30 21:01:39,635 INFO Body: Empty
2024-01-30 21:01:39,635 INFO Headers: Host: 127.0.0.1:5000
Connection: keep-alive
User-Id: 0
Sort-Column: creation_date
Sort-Direction: descending
Dnt: 1
Sec-Ch-Ua: "Not A(Brand";v="99", "Google Chrome";v="121", "Chromium";v="121"
Indexes: ~0~
Sec-Ch-Ua-Mobile: ?1
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/121.0.0.0 Mobile Safari/537.36
Include-Nonsub: true
Sec-Ch-Ua-Platform: "Android"
Accept: */*
Origin: http://localhost:8080
Sec-Fetch-Site: cross-site
Sec-Fetch-Mode: cors
Sec-Fetch-Dest: empty
Referer: http://localhost:8080/
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9,ru-RU;q=0.8,ru;q=0.7,ja;q=0.6


2024-01-30 21:01:39,635 INFO Processed request in 0:00:00.000189: api_pages_get

```

**Comment by abnormalize0** [comment]
Статьи при этом присутствуют в базе данных:
![image](https://github.com/abnormalize0/DailyTeleFrog/assets/61551851/4885c73d-8cdf-4bac-87f9-fc6364a53e74)
И файлы для них тоже существуют:
![image](https://github.com/abnormalize0/DailyTeleFrog/assets/61551851/f1155bab-945d-41f7-a241-35c97867300f)
Для залогиненных пользователи посты отображаются как надо:
![image](https://github.com/abnormalize0/DailyTeleFrog/assets/61551851/c32db4a6-5b74-4794-b895-346d5fcf4e6d)
Ответ для них имеет следующий вид:
![image](https://github.com/abnormalize0/DailyTeleFrog/assets/61551851/416ba641-8999-4ea3-a16a-f274aa9bb3ac)
Фласк отображает при это следующие сообщения:
![image](https://github.com/abnormalize0/DailyTeleFrog/assets/61551851/92269cca-4da2-44c2-bdba-c34d580bb023)
Для незалогинненых пользователей (с идентификатором 0 или -1) посты при этом не отображаются:
![image](https://github.com/abnormalize0/DailyTeleFrog/assets/61551851/b870b58a-89ef-4918-8f98-0eceb5f0f8be)
И в ответе видно что ни один пост не был получен с сервера:
![image](https://github.com/abnormalize0/DailyTeleFrog/assets/61551851/1776e824-a34a-4816-bb69-3317ca28095f)
Фласка при этом не отображает каких-то ошибок
![image](https://github.com/abnormalize0/DailyTeleFrog/assets/61551851/01ea39f4-2c1b-4c6e-9e3e-049e12ba13dd)

**Comment by Roffor** [comment]
Закрыл так как сделано в рамках тикета #109.
