### ISSUE TITLE
Vue md icons integration

### ISSUE THREAD

**Issue by serynabatov** [abnormalize0/DailyTeleFrog#110]
Нужно интегрировать библиотеку иконок vue md (material design)

How to:
1. Линка тут https://pictogrammers.com/docs/library/mdi/getting-started/vuejs/
2. Судя по всему ребята используют другой гит флоу отдельный от классического, потому короч почкуйся от main)

**Comment by waverew** [comment]
добавил мерж реквест

**Comment by waverew** [comment]
удалил ветку с старым названием, убрал ненужный импорт из компонента. Перенес все на другую ветку
