### ISSUE TITLE
Невозможно обратиться к базе данных через API

### ISSUE THREAD

**Issue by abnormalize0** [abnormalize0/DailyTeleFrog#13]
При попытке обратиться к базе данных используя API, сервер возвращает ошибку `TypeError: Object of type set is not JSON serializable`.

**Comment by Roffor** [comment]
Ошибка заключалась в опечатке в методе `add user` из-за чего не проходили все тесты (все тесты добавляют пользователя, так как без пользователей нельзя проверить другой функционал) и нельзя было добавить пользователя. 
Фикс залил напрямую в `main`, так как все исправление состоит из одного символа, и все равно меня некому ревьювить. 
Тикет закрываю.
