### ISSUE TITLE
Дополнить и исправить документацию

### ISSUE THREAD

**Issue by abnormalize0** [abnormalize0/DailyTeleFrog#19]
Необходимо указать в документации полный вывод каждой апишной функции. Исправить очевидные ошибки: неверные индексы, неправильный вывод в примерах.

**Comment by Roffor** [comment]
Документация обновлена и дополнена. Тикет закрываю. Если что-то где-то пропустил, то сделаю в отдельном тикете. 
У нас нет системы ревью и проверки сделанных изменений другими людьми, так что все на моей совести...
