### ISSUE TITLE
Разработать минимальный сервер

### ISSUE THREAD

**Issue by abnormalize0** [abnormalize0/DailyTeleFrog#2]
Создать сервер, обрабатывающий минимальный набор запросов:
* Создание пользователя
* Смена атрибутов пользователя
* Опубликование статьи
* Получение информации о конкретной статье
* Получение списка обложек статей, разбитых на страницы
* Получение количества лайков и комментов конкретной статьи

**Comment by Roffor** [comment]
Добавил первичную версию сервера. 
Запуск сервера осуществляется с помощью файла `start.py` расположенный по пути `/server`. Советую первый запуск осуществить с помощью команды `start.py -h`. Это позволит посмотреть доступные опции.
Допустимые для сервера запросы располагаются в файле `api.py`, расположенный по пути `/server`.

**Comment by Roffor** [comment]
Добавил обработку запросов на смену пароля, проверку пароля и обновление любого поля кроме полей пароля, id и логина. Убран остаточный дебажный код, который я пропустил, когда пушил предыдущие коммиты. 
Считаю, что минимальный функционал сервера разработан. 
Тикет пока не закрываю, так как не протестирована связка сервера и сайта. После тестов и возможных исправлений тикет закрою.

**Comment by Roffor** [comment]
Связка сайта и сервера протестирована с помощью тестов на апи, тикет закрываю.
