### ISSUE TITLE
Разработать тесты на API и работу с базой данных

### ISSUE THREAD

**Issue by Roffor** [abnormalize0/DailyTeleFrog#3]
Необходимо разработать две группы тестов, которые покроют весь текущий функционал:
* Тесты на API сервера
   * должны проверять все существующие типы запросов
   * должны проверять корректность работы сервера при подаче неправильных данных
* Тесты работы с базой данных
   * должны проверять все типы запросов к базе данных
   * должны проверять корректность работы сервера при наличии неправильных данных в базе данных
   * должны проверять корректность работы сервера при подаче неверных данных в запрос

**Comment by Roffor** [comment]
От тестов базы данных временно отказались, так как они бессмысленны без обработки ошибок. 
Обработка ошибок запланирована сразу после документации. Поэтому тесты базы данных в этом тикете не будут реализованы. На них будет создан новый тикет.

**Comment by abnormalize0** [comment]
Реквесты, содержащие хедеры, в названии которых есть символ подчеркивания, работают некорректно. Вместо переданных значений на выходе получатель принимает None. Проблема наблюдается только на Windows 11, определить причину пока не представляется возможным. 
Результат на win11:
![image](https://github.com/abnormalize0/DailyTeleFrog/assets/61551851/281e24bc-2c27-45b6-b029-93f355311662)
Результат на win10:
![image](https://github.com/abnormalize0/DailyTeleFrog/assets/61551851/df018bb0-794f-4489-8429-bd62de046e31)

**Comment by Roffor** [comment]
Дополню комментарий Михаила парой уточнений.
* В умных интернетах пишут, что названия заголовков (_headers_) не должны содержать подчеркивания. Михаил оставит одну или несколько ссылок на такой материал.
* Заголовки, содержащие подчеркивания, отсекаются где-то между передачей сообщения и получением сообщения сервером. Причем не все. Например, `user_id` проходит. Почему так непонятно.
* Изначально на windows 11 у меня все работало корректно. Потом я внес пару исправлений и залил их не проверив(атата мне, больше так не буду). В этих обновлениях были допущены ошибки. После починки этих ошибок тесты не запускаются. Откат на старую версию в гите тоже не решил проблему. Почему непонятно.
* Мы вдвоем решили, что проще обойти проблему (заменить все подчеркивания на дефисы), чем пытаться решить проблему. Мы суммарно потратили что-то около 10чч и не сильно приблизились к пониманию проблемы и ее решению. Вместо бесконечного исследования целесообразнее временно обойти проблему. Надеюсь в будущем у нас хватит компетенции понять, что произошло.

В остальном тикет можно закрывать, так как тесты добавлены и проходят. С уточнением, что тесты на данный момент проверяют, что апи работает в минимальном режиме. Более полное тестирование апи и сервера будет реализовано после добавления обработки ошибок на стороне сервера.

**Comment by abnormalize0** [comment]
Несколько ссылок по поводу использования подчеркиваний в заголовках
https://www.grouparoo.com/blog/dont-use-underscores-in-http-headers
https://dev.to/thesameeric/dont-use-underscores-in-your-http-headers-gfp
