### ISSUE TITLE
Хочу поиск по тегам, автору, дате и т.д

### ISSUE THREAD

**Issue by Roffor** [abnormalize0/DailyTeleFrog#43]
Даже добавить нечего.

В рамках тикета необходимо реализовать функционал на беке и поддержать его на фронте.

**Comment by Roffor** [comment]
Добавить теперь есть чего. 
Что хочется реализовать в данном тикете:
Для апи запроса `api_pages_get` будут введены следующие обязательные заголовки:
1. type
2. include_articles_without_sub

И следующие необязательные:

1. sort
2. upper_limit
3. lower_limit
4. include_tags
5. exclude_tags
6. include_authors
7. exclude_authors
8. include_community
9. exclude_community

Заголовок `type` хранит в себе одну из следующих строк: `data`, `rating`, `popularity`.
Заголовок `sort` хранит в себе одну из следующих строк: `descending`, `ascending`.
Заголовок `upper_limit` хранит в себе значение ограничение сверху для данной сортировки.
Заголовок `lower_limit` хранит в себе значение ограничение снизу для данной сортировки.
Заголовок `include_tags` хранит в себе теги, которые должны быть у статьи. Все из перечисленных тегов должны присутствовать у статьи. Нужен ли нам вариант с поиском через или? когда хотя бы один или только один из группы должен присутствовать? Мне кажется, что для релиза не нужно, но тут возможно есть сценарий, о котором я не знаю.
Заголовок `exclude_tags` хранит в себе теги, которых не должно быть у статей в выборке.
Заголовок `include_articles_without_sub` хранит в себе `True` или `False`. Значение `True` указывает, что в выдачу нужно включить статьи, которые не содержат тегов, авторов и сообществ, на которых пользователь не подписан. Значение же `False` указывает, что такие статьи не должны присутствовать в выдаче.

Как это должно работать:
Теперь с помощью метода `api_pages_get` можно будет получить не просто статьи, а различные _ленты_.
Например, ленту лучшее можно получить, если поставить сортировку по рейтингу по убыванию без ограничений.
Ленту свежего получить можно аналогично, поставив сортировку по дате по убыванию (в контексте даты самой большой датой считается самая поздняя, то есть 01.01.2022 > 09.09.2021). 

Поиск по тегам/автору/сообществу осуществляется через дополнительные заголовки, начинающиеся на `include` или `exclude` для включения или исключения из выдачи соответственно.
**В рамках этого тикета не будет реализован поиск по ключевым словам.**

Также здесь уместно рассмотреть как предполагается возвращение пользователя в ленту. Если пользователь листает ленту, то он всегда должен находится на предпоследней подгруженной странице. Когда пользователь переходит в статью, то он вернется в свою же подгруженную предпоследнюю страницу. Последняя страница должна быть обновлена. Фронту необходимо послать запрос аля _"Сервер выдай мне статьи, отсортированные по убыванию XXX, но не более YYY"_, где _XXX_ - это дата/рейтинг/популярность, а _YYY_ - это значение параметра _XXX_ у последней статьи на момент первой загрузки страницы. Таким образом, если пользователь зашел в статью с рейтингом 1000, просидел в ней 5 минут и рейтинг статьи изменился, то он вернется **ПРИМЕРНО** в то же место в ленте, где он и был.

**Comment by abnormalize0** [comment]
Проблема данной предполагаемой реализации в том что я например не могу вывести самые популярные посты за месяц. И я не понимаю как должен сортировать посты тип `popularity`.

**Comment by Roffor** [comment]
Ок, `popularity` на самом деле не нужен.

По поводу сортировки лучшего за месяц, можно добавить еще один заголовок. То есть вместо `upper_limit` и
`lower_limit` будут `upper_date`, `upper_rating`, `lower_date` и `lower_rating`.

**Comment by abnormalize0** [comment]
Да, приемлемо.

**Comment by Roffor** [comment]
Сделано. Тесты написаны и проходят без падений. Залито в мастер.
Все обнаруженные ошибки нарекаю багами и предлагаю решать в рамках отдельных задач.
Из известного - если пользователь сделает поиск по тегу/автору/сообществу, которые находятся у него в черном списке, то он получит пустую выдачу. Ожидаемое поведение - получит выборку с игнорированием части черного списка. Но насколько это нужно вопрос открытый, так что решать буду тоже в рамках отдельного тикета и не скоро.
