### ISSUE TITLE
Обрабатывать запросы от пользователей не зарегистрированных на сайте

### ISSUE THREAD

**Issue by abnormalize0** [abnormalize0/DailyTeleFrog#55]
Реализовать корректную обработку запросов от пользователей с идентификатором 0 как не зарегистрированных, с соответствующими ограничениями (невозможность поставить лайк, создать пост и т.д.), оставив при этом возможность получать посты.

**Comment by Roffor** [comment]
Залито в мастер. Тесты прошли, тикет закрываю.
