### ISSUE TITLE
Изменить поведение API проверки пароля

### ISSUE THREAD

**Issue by abnormalize0** [abnormalize0/DailyTeleFrog#57]
API проверки пароля должен возвращать is-correct: false в случае если  был отправлен логин которого не существует.

**Comment by Roffor** [comment]
Короче будет исправлено в рамках #14. Есть подозрение, что эти две проблемы и еще пачка боли уйдет за счет использования фласки.
Закрывать на всякий случай не буду. Закрою, если проблема уйдет после закрытия #14.

**Comment by Roffor** [comment]
Исправил в итоге в рамках #35 
@abnormalize0 проверь, если работает так, как ты хотел, то тикет закрою.

**Comment by Roffor** [comment]
Так как никто не ответил, тикет закрываю.
