### ISSUE TITLE
Реализовать метод который будет возвращать информацию о пользователе.

### ISSUE THREAD

**Issue by abnormalize0** [abnormalize0/DailyTeleFrog#62]
Нужен метод который будет по логину возвращать имя профиля, аватар, рейтинг, дату регистрации. В дальнейшем его надо будет расширить и добавить описание профиля, число подписчиков и подписок, историю имен.

**Comment by Roffor** [comment]
Добавил АПИ для доступа к данным о пользователе. На данный момент возвращаются вообще все данные без каких-либо исключений. Пока структура данных, которые хранятся в бд о пользователях не устаканилась, поэтому и думать или делать какую-ту выборку из этих данных, я не хочу.

Тесты на метод добавлены. В документации запись о новом методе находится в разделе АПИ методов.

**Comment by abnormalize0** [comment]
Все еще хочу описание профиля, дату регистрации, историю имен, ну и рейтинг с числами подписок и подписчиков.

**Comment by Roffor** [comment]
Описание профиля реализую в рамках этого тикета.
История имен, рейтинг и подписки будут реализованы в отдельных тикетах (на каждое поле свой тикет), так требуют разных функциональных изменений.

**Comment by Roffor** [comment]
Залил новое поле - описание профиля. Работа с ним происходит через стандартные методы `api_users_data_post` и `api_users_data_get`. На оставшиеся из этого тикета параметры создам отдельные тикеты.
