### ISSUE TITLE
Изменить API лайков/дизлайков.

### ISSUE THREAD

**Issue by abnormalize0** [abnormalize0/DailyTeleFrog#69]
Надо изменить API:
* Унифицировать запросы, уменьшив их число;
* Вместо списка пользователей поставивших лайк/дизлайк ввести поле, в котором будет информация, поставил ли текущий пользователь лайк/дизлайк или нет;
* Исправить документацию.

**Comment by Roffor** [comment]
Пункт
> Унифицировать запросы, уменьшив их число 
Выполнен в рамках #35

**Comment by Roffor** [comment]
Тикет последователь: https://github.com/abnormalize0/DailyTeleFrog/issues/101
Этот закрываю.
