### ISSUE TITLE
Выборка постов

### ISSUE THREAD

**Issue by abnormalize0** [abnormalize0/DailyTeleFrog#70]
Сделать для постов выборку по тегам и по пользователям.

**Comment by Roffor** [comment]
Вообще не понятно что хотели и в каком виде. 
Нужны ответы на вопросы:
1. Что нужно сделать?
2. Зачем нужно сделать?
3. Какой сценарий использования?

Это прям минимум. А тут из этого ноль. Я не могу угадывать, что ты хотел, чтобы было сделано.

**Comment by abnormalize0** [comment]
Да, стоило дать хоть какое-то описание. В моей оно звучало слишком очевидно чтоб давать дополнительные пояснения. В любом случае закрываю потому что это дубликат.
