### ISSUE TITLE
Не могу получить страницу, если по запросу доступна всего одна статья

### ISSUE THREAD

**Issue by abnormalize0** [abnormalize0/DailyTeleFrog#76]
В данный момент если попытаться получить статьи методом api_get_pages, в то время как существует всего одна статья, сервер возвращает следующую ошибку:

> File "/mnt/c/users/mixai/Desktop/DailyTeleFrog/server/src/backend.py", line 13, in get_page_articles
    if len(articles) < (index + 1) * config.articles_per_page:
TypeError: object of type 'int' has no len()

Потенциально может быть проблемным при выборках по тегу или пользователю, так что надо исправить в обозримом будущем.

**Comment by Roffor** [comment]
Таких названий тикетов не должно быть.  В названии тикета должно быть указано правильное/ожидаемое поведение со пометкой, что что-то не работает/ работает не так как хочется.
В случае бага стоит писать в названии наблюдаемое неправильное поведение. Например, `Не могу получить страницу, если по запросу доступна всего одна статья`. Название тикета необходимо переписать. 
По нашему соглашению я не делаю тикеты с тегом _**Bad description**_

**Comment by Roffor** [comment]
Исправлено, изменения в мастере, тесты теперь учитывают этот случай.
